### COMP120 - Mastery Tasks 09
#==============================
# Student ID: 5120768
# Name: Son Hoang Nguyen (Alex)
#==============================
# Your code for the mastery task should be provided below.
# Make sure you write comments about what your code does for each block of code that you write.

# Load the appropriate packages/libraries for this mastery task. Code for one of them is given below.
library(tidyverse)
library(randomForest)

# A random seed has been set for you. You must execute this line before creating training and test data so that the results are reproducible (i.e., will provide the same results everytime and it is easy to check the answers)
set.seed(1001) ## FIX THE RANDOM NUMBER GENERATOR FOR REPRODUCIBILITY

# Write code to create diamonds2 dataset. Also, write code to partition this dataset into the training and test data
diamonds2 <- diamonds %>% filter(carat <= 2.5)

train <- diamonds2 %>% sample_frac(0.9)
test <- diamonds2 %>% setdiff(train)


# Code and comments for the first linear model (model1) for question 1 - indicate the 
# sub-questions you are answering - e.g. #a), #b) and #c)

f <- price ~ carat
# a)	Write code to construct the model using the training dataset.
model1 <- lm(f, train)
summary(model1)

# b)	Write down the resulting regression equation: Y = -2334.40 + 7866.22X1

# c>	Describe the impact of carat on price. 
# When the diamond weight 0 carat, the price is -$2334.40. Which does not really make sense.
# Each additional carat results in an increase by about $7866.22 in price of the diamond.

# d)	Write code to obtain the R-squared value for the training dataset.  
mdl1 <- summary(model1)
mdl1$r.squared

# e)	Write a comment showing the value of the R-squared result in question d above.
# The Rsquare value for the training dataset is 0.8528.
# the R2 statistic suggests that 85.28% of the variance is captured by the model

# f)	Write code to predict the outcomes for the test dataset. 
yhat <- predict(model1, test)

# g)	Write code to obtain the R-squared value for the test dataset. 
# Compute R square statustic for the  data
rsqr <- function(y, yhat) {
  ss.res <- sum((y - yhat)^2)
  ss.tot <- sum((y - mean(y))^2)
  
  1 - ss.res / ss.tot
}

rsqr(test$price, yhat)
# The R-squared value for the test dataset is 0.844. 
# the R2 statistic suggests that 84.4% of the variance is captured by the model generated by train dataset

#h)	Write code to generate the residual plot for the test dataset.
test_mod <- test %>% mutate(residual = price - yhat)

# Visualise the residual plot
ggplot(test_mod, aes(x=price, y=residual)) +
  geom_point(aes(alpha=0.01)) + 
  geom_abline(slope = 0, intercept=0, col = "red") + 
  ggtitle("Diamond Price vs. residual") +
  xlab("Diamond Price") + 
  ylab("Residual")


ggplot(test_mod, aes(price, carat))+
  geom_point(col="blue")+
  geom_smooth(method = "lm", se=FALSE, col="red")+
  ggtitle("Price vs carat")


#i)	Describe the result of the residual plot
# Residual values are are distributed randomly. 
# Residuals form straight lines for certain carat values. This could potentially be a rounding
# issue with the way carat was measured. Maybe people tend to round the carat value.

# also, The higher the carat value, the higher values of variations. In other words,
# There are some heavy diamonds(high carat values) were sold at very high price, while some were sold at low price





# Code and comments for the second model, a random forest model (model2) for question 2 - indicate the 
# sub-questions you are answering - e.g. #a), #b) and #c)
#a. construct the model using the training dataset
model2 <- randomForest(f, train, ntree=100)

#b.
mean(model2$rsq)

#c.	Write code to predict the outcomes for the test dataset. 
yhat <- predict(model2, test)

# d.	Write code to obtain the R-squared value for the test dataset. 
rsqr(test$price, yhat)
# R-square for the test dataset is 0.8613. 
# 86.13% of the variation in test is captured by the randomforest model2

#e.	Write code to generate the residual plot for the test dataset.
# Create a new variable that has all the columns of the test dataset # plus the residual variable
test_mod <- test %>% mutate(residual = price - yhat)

# Visualise the residual plot
ggplot(test_mod, aes(x=price, y=residual)) +
  geom_point(aes(alpha=0.1)) + 
  geom_abline(slope = 0, intercept=0, col = "red") + 
  ggtitle("Diamond Price vs. residual") +
  xlab("Diamond Price") + 
  ylab("Residual")


# Answer for question 3 
# The R-squared value for the test dataset for model 1 is 0.844.
# The R-squared value for the test dataset for model 2 is 0.8613.
# We can see that model2 did a better job at predicting price of unseen diamonds 
# based on its weight(carat). R-square value of model2 is higher!

